version: '3.8'
services:
  mongodb:
    image: mongo:7.0
    container_name: geekblog-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: geekblog
    volumes:
      - mongodb_data:/data/db
    # mongodb 的端口可以不向外暴露了，因为只有 backend 服务需要访问它
    # ports:
    #   - "27017:27017" # 注释掉或删除，更安全
    networks:
      - geekblog-network

  backend:
    build: ./backend
    container_name: geekblog-backend
    restart: always
    environment:
      PORT: 8080
      MONGO_URI: mongodb://admin:password123@mongodb:27017/geekblog?authSource=admin
      DB_NAME: geekblog
      JWT_SECRET: your-secret-key-change-this
      UPLOAD_PATH: /app/uploads
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongodb
    ports:
      # 将端口绑定到 127.0.0.1 (localhost)，只有本机能访问
      - "127.0.0.1:8080:8080"
    networks:
      - geekblog-network

  frontend:
    build: ./frontend
    container_name: geekblog-frontend
    restart: always
    environment:
      REACT_APP_API_URL: /api
    depends_on:
      - backend
    ports:
      # 将端口绑定到 127.0.0.1 (localhost)，只有本机能访问
      # 我们用 3000 端口来接收前端的请求
      - "127.0.0.1:3000:80"
    networks:
      - geekblog-network

# NGINX 服务已被完全删除

volumes:
  mongodb_data:

networks:
  geekblog-network:
    driver: bridge
